'use strict';

module.exports = {
    'no-getter-contains-more-than-return-statement': require('./no-getter-contains-more-than-return-statement'),
    'no-assignment-expression-assigns-value-to-member-variable': require('./no-assignment-expression-assigns-value-to-member-variable'),
    'no-wire-config-references-non-local-property-reactive-value': require('./no-wire-config-references-non-local-property-reactive-value'),
    'no-private-wire-config-property': require('./no-private-wire-config-property'),
    'no-unresolved-parent-class-reference': require('./no-unresolved-parent-class-reference'),
    'no-class-refers-to-parent-class-from-unsupported-namespace': require('./no-class-refers-to-parent-class-from-unsupported-namespace'),
    'no-reference-to-unsupported-namespace-reference': require('./no-reference-to-unsupported-namespace-reference'),
    'no-wire-config-property-uses-getter-function-returning-inaccessible-import': require('./no-wire-config-property-uses-getter-function-returning-inaccessible-import'),
    'no-wire-config-property-uses-getter-function-returning-non-literal': require('./no-wire-config-property-uses-getter-function-returning-non-literal'),
    'no-wire-config-property-circular-wire-dependency': require('./no-wire-config-property-circular-wire-dependency'),
    'no-wire-configuration-property-using-output-of-non-primeable-wire': require('./no-wire-configuration-property-using-output-of-non-primeable-wire'),
    'no-missing-resource-cannot-prime-wire-adapter': require('./no-missing-resource-cannot-prime-wire-adapter'),
    'no-wire-config-property-uses-imported-artifact-from-unsupported-namespace': require('./no-wire-config-property-uses-imported-artifact-from-unsupported-namespace'),
    'no-wire-adapter-of-resource-cannot-be-primed': require('./no-wire-adapter-of-resource-cannot-be-primed'),
    'no-unsupported-member-variable-in-member-expression': require('./no-unsupported-member-variable-in-member-expression'),
    'no-multiple-template-files': require('./no-multiple-template-files'),
    'no-composition-on-unanalyzable-getter-property': require('./no-composition-on-unanalyzable-getter-property'),
    'no-composition-on-unanalyzable-property-from-unresolvable-wire': require('./no-composition-on-unanalyzable-property-from-unresolvable-wire'),
    'no-composition-on-unanalyzable-property-non-public': require('./no-composition-on-unanalyzable-property-non-public'),
    'no-composition-on-unanalyzable-property-missing': require('./no-composition-on-unanalyzable-property-missing'),
    'no-assignment-expression-for-external-components': require('./no-assignment-expression-for-external-components'),
    'no-expression-contains-module-level-variable-ref': require('./no-expression-contains-module-level-variable-ref'),
    'no-call-expression-references-unsupported-namespace': require('./no-call-expression-references-unsupported-namespace'),
    'no-eval-usage': require('./no-eval-usage'),
    'no-reference-to-class-functions': require('./no-reference-to-class-functions'),
    'no-reference-to-module-functions': require('./no-reference-to-module-functions'),
    'no-functions-declared-within-getter-method': require('./no-functions-declared-within-getter-method'),
    'no-member-expression-reference-to-non-existent-member-variable': require('./no-member-expression-reference-to-non-existent-member-variable'),
    'no-member-expression-reference-to-unsupported-namespace-reference': require('./no-member-expression-reference-to-unsupported-namespace-reference'),
    'no-member-expression-contains-non-portable-identifier': require('./no-member-expression-contains-non-portable-identifier'),
    'no-member-expression-reference-to-super-class': require('./no-member-expression-reference-to-super-class'),
    'no-member-expression-reference-to-unsupported-global': require('./no-member-expression-reference-to-unsupported-global'),

    // TODO: These rules do not have tests because Komaci itself did not have tests for them.
    'no-tagged-template-expression-contains-unsupported-namespace': require('./no-tagged-template-expression-contains-unsupported-namespace'),
    'no-render-function-contains-more-than-return-statement': require('./no-render-function-contains-more-than-return-statement'),
    'no-render-function-return-statement-not-returning-imported-template': require('./no-render-function-return-statement-not-returning-imported-template'),
    'no-render-function-return-statement': require('./no-render-function-return-statement')
};
